Add new HEAD method to return entry metadata without reading entire record
reductstore/reductstore pull request #229
Opened 2023-01-11 20:52 UTC by rtadepalli

Closes #214 

### Please check if the PR fulfills these requirements

- [X] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] CHANGELOG.md have been updated (for bug fixes / features / docs)

### What kind of change does this PR introduce?
This PR introduces a new HTTP endpoint of type HEAD that returns entry metadata without reading the entire record. It is functionally similar to the GET endpoint, except we return everything else except the record content.

(Bug fix, feature, docs update, ...)

### What is the current behavior?

This API does not exist right now, this is a new feature.

### What is the new behavior?

This is a new feature.

### Does this PR introduce a breaking change?

No, there are no breaking changes because of this PR.

2023-01-11 20:52 UTC, rtadepalli commented
I will update documentation once the core changes look satisfactory.

2023-01-13 20:30 UTC, atimin requested changes
Thank you for your contribution. Almost perfect! Please see my comments and check the pipeline.   `cpplint` isn"t happy ;).  You can use `pre-commit` to check the format automatically when you make a commit.

2023-01-13 20:30 UTC, atimin commented on api_tests/entry_api_test.py
> +    ts = 1000
Some little doc string is missing. Something like "should return only headers"

2023-01-13 20:30 UTC, atimin commented on api_tests/entry_api_test.py
> +
I would like to add a test for error. Ask, please, for a non-existing record and check "x-reduct-error"

2023-01-13 20:30 UTC, atimin commented on src/reduct/api/entry_api.cc
> +                    [reader, send_record_data]() {
this is completely fine to pass "send_record_data into the lambda. Consider using the flag to create two different lambdas.

2023-01-16 20:52 UTC, atimin reviewed
Unfortunately, I found another problem. Check http_server.cc:219:

```cpp
 auto [ok, responded] =
            ctx.res->tryEnd(chuck.substr(ctx.res->getWriteOffset() - offset), response.content_length);
        if (ok) {
          complete = responded;
          break;
```

We use the `content_length` for sending data. When we send an empty string but say the size is greater than 0, the HTTP connection hangs.  We should work around the case for the HEAD request. 

WebSocket framework sets the "Content-Length" header automatically, not sure if it is possible to send an empty trying but have the non-zero header. I'll check myself

2023-01-20 07:59 UTC, atimin commented
Blocked by uNetworking/uWebSockets#1557

2023-04-10 23:55 UTC, merged

2023-04-10 23:56 UTC, atimin commented
@rtadepalli I've merged it to keep your contribution after Rust migration.